# This is a config for E2B sandbox template.
# You can use template ID (z585f2vd5jfirs0qpl4x) or template name (pipilot) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("pipilot") # Sync sandbox
# sandbox = await AsyncSandbox.create("pipilot") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('pipilot')

team_id = "ff70324b-51eb-42dc-ad33-d062bf0099e7"
dockerfile = "e2b.Dockerfile"
template_name = "pipilot"
template_id = "z585f2vd5jfirs0qpl4x"

# CPU and RAM configuration (Pro plan required for customization)
cpu_count = 2
memory_mb = 4096
