name: Deploy to Vercel

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

env:
  SUPABASE_URL: "https://lzuknbfbvpuscpammwzg.supabase.co"
  SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dWtuYmZidnB1c2NwYW1td3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDM3NjIsImV4cCI6MjA3MTI3OTc2Mn0.bi3kpj741AZ7eDYBYs72LXKG754T2cBfBqd8EHV1Gvo"
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6dWtuYmZidnB1c2NwYW1td3pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDM3NjIsImV4cCI6MjA3MTI3OTc2Mn0.bi3kpj741AZ7eDYBYs72LXKG754T2cBfBqd8EHV1Gvo"
  VERCEL_TOKEN: "B6lPmCaHcgvLrAxtSadKYcNu"

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ env.VERCEL_TOKEN }} --yes